### ISSUE TITLE
Strange mismatch in docs

### ISSUE THREAD

**Issue by johnmcilwain** [jeffcarp/luhn-rs#4]
Hi, it is probably me as I am a beginner, but the docs here:
https://crates.io/crates/luhn
Show a dependency of:
luhn = "0.1.0"

But this shows correct:
https://github.com/jeffcarp/luhn-rs
luhn = "1.0.0"

Thought I would throw this out there as I tried 0.1.0 as the version initially when trying the crate...
But I am also confused on "luhn" vs "luhn-rs" and if there is a conflict somewhere.
https://docs.rs/luhn-rs/0.0.1/luhn/ -> this calls it "luhn" but has "luhn-rs" in the directory...

Again, a beginner, so probably have this completely wrong.

thx!

**Comment by jeffcarp** [comment]
Thanks for pointing this out, it looks like the crates page is pointing to an [old version of README.md](https://github.com/jeffcarp/luhn-rs/blob/92f75eb5d291785dc2791734b1d52d7df016798e/README.md). This is because I [updated the version in README.md](https://github.com/jeffcarp/luhn-rs/commit/5b1fc445bd0bc64b062f4c63d19e3fd3572397ba) after I pushed 1.0.0 to crates.io.

Good question, it looks like the crate `luhn-rs` [sets its library target name to `luhn`](https://github.com/andrew-d/luhn-rs/blob/master/Cargo.toml#L13).

I will bump this crate to 1.0.1 and redeploy the package, which will fix the README on crates.io.

**Comment by jeffcarp** [comment]
[Fixed](https://crates.io/crates/luhn)
